Remove `--production` flag from `npm install`
PermanentOrg/upload-service pull request #30
Opened 2021-01-28 16:51 UTC by andrewatwood

As written, the service runs using `babel-node` directly from the TypeScript source. Babel is currently listed under `devDependencies` and isn't installed using the `--production` flag. For now, we won't change this, and will just remove this flag so that all dependencies get installed for the `tar` that gets created.

Potentially in the future, we could adjust this configuration to run from transpiled Javascript using `node` directly, but in the interest of making the minimum change, this is the approach I think we should take.

2021-01-28 19:21 UTC, jasonaowen requested changes
This is a good start, but I don't think this is a complete solution.

What I would like for us to do is to build this here, with the dev dependencies installed and then archive the build artifacts. Then, on the server, we should deploy the build artifacts and install only the production dependencies.

2021-01-28 19:36 UTC, andrewatwood commented
Oh yes, after reviewing [the service definition](https://github.com/PermanentOrg/infrastructure/blob/cc441eb2565356577d5b8dc5a4879d17b113a54f/templates/etc/systemd/system/node-upload.service#L8) I see it is running the `/lib` output after all. I'd incorrectly assumed that `npm start` was being used to run it when actually deployed, which isn't the case.

Will go back to the original plan then, which aligns with your suggestion.

2021-01-29 02:08 UTC, andrewatwood commented
More changes incoming! Realized I didn't make the full change to only archive the build and not any dependencies.

2021-01-29 19:06 UTC, cecilia-donnelly commented
So, with this change we'd then need to add an action to the [deploy-backend](https://github.com/PermanentOrg/infrastructure/blob/main/provisioners/deploy-backend.yml) provisioner that runs `npm install` after untarring `upload-service`?  Or would it belong somewhere else?

2021-01-29 19:12 UTC, andrewatwood commented
Exactly!

I believe I found the place to do it: https://github.com/PermanentOrg/infrastructure/pull/41

2021-01-29 19:38 UTC, cecilia-donnelly approved these changes
With the [infra PR](https://github.com/PermanentOrg/infrastructure/pull/41), this looks good!

2021-01-29 19:41 UTC, merged